apiVersion: v1
kind: Pod
metadata:
 name: nginx
 labels:
  environment: QA
  app: frontend
spec:
 containers:
  - name: nginx
    image: nginx
    ports:
     - name: htt-web-svc
       containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
 name: nginx-service
spec:
 type: LoadBalancer
 selector:
  environment: QA
  app: frontend
 ports:
  - name: name-of-service-port
    protocol: TCP
    port: 80
    targetPort: http-web-svc
    nodePort: 30002
...