apiVersion: v1
kind: ConfigMap
metadata:
 name: filebeat-configmap
data:
 filebeat.yml: |
  filebeat:
    config:
      modules:
        path: /usr/share/filebeat/modules.d/*.yml
        reload:
          enabled: true
    modules:
    - module: nginx
      access:
        var.paths: ["/var/log/nginx/access.log*"]
      error:
        var.paths: ["/var/log/nginx/error.log*"]
  output:
    elasticsearch:
      hosts: ["elasticsearch:9200"]
--- 
apiVersion: apps/v1
kind: Deployment
metadata:
 name: nginx
 labels:
  environment: Dev
  app: nginx
  project: roboshop
spec:
 replicas: 1
 selector:
  matchLabels:
   environment: Dev
   app: nginx
   project: roboshop
 template:
  metadata:
   labels:
    environment: Dev
    app: nginx
    project: roboshop
  spec:
   volumes:
    - name: nginx-logs
      emptyDir: {}
    - name: filebeat-config
      configMap:
       name: filebeat-configmap
       items:
        - key: filebeat.yml
          path: filebeat.yml
   containers:
    - name: nginx
      image: nginx
      ports:
       - containerPort: 80
      volumeMounts:
       - name: nginx-logs
         mountPath: var/log/nginx/
       - name: filebeat-config
         mountPath: /usr/share/filebeat/filebeat.yml
         subPath: filebeat.yml
         