apiVersion: v1
kind: PersistentVolume
metadata:
  name: ebs-static
spec:
  storageClassName: ""
  accessModes:
  - ReadWriteOnce
  awsElasticBlockStore:
    fsType: ext4
    volumeID: vol-0a129935e3209d4e4
  capacity:
    storage: 10Gi