apiVersion: v1
kind: PersistentVolume 
metadata:
 name: ebs-static
spec:
 storageClassName: ""
 accessModes:
  - ReadWriteOnce
 awsElasticBlockStore:
  fsType: ext4
  volumeID: vol-07552ca3d94f8464a
 capacity:
  storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: ebs-static-pvc
spec:
 storageClassName: ""
 accessModes:
  - ReadWriteOnce
 resources:
  requests:
   storage: 3Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: nginx-deployment
 labels: # these labels belong to deployment
  app: nginx
spec:
 replicas: 1
 selector:
  matchLabels: # these labels should match with pod
   environemnt: Dev
   app: nginx
   project: roboshop
 template: # this is the pod definition
  metadata:
   labels:
    environemnt: Dev
    app: nginx
    project: roboshop
  spec:
   containers:
    - name: nginx
      image: nginx:1.14.2
      ports:
       - containerPort: 80
      volumeMounts:
       - name: nginx-html
         mountPath: /usr/share/nginx/html
   volumes:
    - name: nginx-html
      persistentVolumeClaim: # this is the PVC
       claimName: ebs-static-pvc