apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
 name: ebs-sc
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
parameters:
  csi.storage.k8s.io/fstype: xfs
  type: io1
  iopsPerGB: "50"
  encrypted: "true"
#reclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: ebs-dymainc-pvc
spec:
 storageClassName: "ebs-sc"
 accessModes:
  - ReadWriteOnce
 resources:
  requests:
   storage: 4Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: nginx-deployment
 labels:
  environment: Dev
  app: nginx
  project: roboshop
spec:
 replicas: 1
 selector:
  matchLabels:
    environment: Dev
    app: nginx
    project: roboshop
 template:
  metadata:
   labels:
    environment: Dev
    app: nginx
    project: roboshop
  spec:
   containers:
    - name: nginx
      image: nginx:1.14.2
      ports:
       - name: http-web
         containerPort: 80
      volumeMounts:
       - name: nginx-html
         mountPath: "/usr/share/nginx/html"
   volumes:
    - name: nginx-html
      persistentVolumeClaim:
       claimName: ebs-dynamic-pvc
