apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: efs-dynamic-roboshop-sc
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-010021bbf6d25274c
  directoryPerms: "700"
  gidRangeStart: "1000" # optional
  gidRangeEnd: "2000" # optional
  basePath: "/roboshop" # optional
reclaimPolicy: Retain
  # ensureUniqueDirectory: "true" # optional
  # reuseAccessPoint: "false" # optional
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: efs-dynamic-pvc
spec:
 storageClassName: "efs-dynamic-roboshop-sc"
 accessModes:
  - ReadWriteOnce
 resources:
  requests:
   storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: nginx-deployment
 labels:
  app: nginx
spec:
 replicas: 2
 selector:
  matchLabels:
   app: nginx
   project: roboshop
   component: frontend
 template:
  metadata:
   labels:
    app: nginx
    project: roboshop
    component: frontend
  spec:
   containers:
    - name: nginx
      image: nginx:1.14.2
      ports:
       - containerPort: 80
      volumeMounts:
       - name: nginx-html
         mountPath: "/usr/share/nginx/html"
   volumes:
    - name: nginx-html
      persistentVolumeClaim:
       claimName: efs-dynamic-pvc