apiVersion: v1
kind: Pod
metadata:
 name: annotations
 annotations:
  com.project.author: Siva Medam
  com.project.name: roboshop
spec:
 containers:
  - name: nginx-labels
    image: nginx
    ports: 
     - containerPort: 80