apiVersion: v1
kind: Pod
metadata:
 name: resources
spec:
 containers:
  - name: image
    image: nginx
    imagePullPolicy: always
    resources:
     requests:
      cpu: "100m"
      memory: "128Mi"
     limits:
      cpu: "200m"
      memory: "256Mi"
