apiVersion: v1
kind: Pod
metadata:
 name: resources
spec:
 containers:
  - name: image
    image: nginx
    imagePullPolicy: Always
    resources:
     requests:
      cpu: "125m"
      memory: "128Mi"
    limits:
     cpu: "250m"
     memory: "256Mi"
