apiVersion: v1
kind: Pod
metadata:
 name: config-pod
spec:
 containers:
  - name: nginx
    image: nginx
    env:
     - name: COURSE
       valueFrom:
        confipMapKeyRef:
         name: course-config
         key: COURSE
     - name: PERSON
       valueFrom:
        configMapKeyRef: 
         name: course-config
         key: TRAINER
     - name: DURATION
       valueFrom:
        name: course-config
        key: DURATION