apiVersion: v1
kind: Secret
metadata:
 name: secret-basic-auth
data:
 username: U2l2YSBNZWRhbQo=
 password: U2l2YUAxMjMK
---
apiVersion: v1
kind: Pod
metadata:
 name: secret-pod
spec:
 containers:
  - name: nginx
    image: nginx
    envFrom:
     - secretRef:
        name: secret-basic-auth